<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Comment extends Model
{
    use Searchable;
    protected $fillable = ['content', 'seen', 'design_id', 'user_id'];
    protected $with = ['user'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('order', function (Builder $builder){
           $builder->orderBy('created_at', 'desc');
        });
    }

    public function design()
    {
        return $this->belongsTo(Design::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        $array = $this->only('content');

        return $array;
    }
}
